= What is log injections and why it is underestimated?

Log injections consist to inject fake entries into logs file.

# Log4J2 layouts

image::https://www.planete-secu.com/wp-content/uploads/billet-pourquoi-site-http-vulnerables.svg[http vs https]

Inter haec Orfitus praefecti potestate regebat urbem aeternam ultra modum delatae dignitatis sese efferens insolenter, vir quidem prudens et forensium negotiorum oppido gnarus, sed splendore liberalium doctrinarum minus quam nobilem decuerat institutus, quo administrante seditiones sunt concitatae graves ob inopiam vini: huius avidis usibus vulgus intentum ad motus asperos excitatur et crebros.

Et quoniam mirari posse quosdam peregrinos existimo haec lecturos forsitan, si contigerit, quamobrem cum oratio ad ea monstranda deflexerit quae Romae gererentur, nihil praeter seditiones narratur et tabernas et vilitates harum similis alias, summatim causas perstringam nusquam a veritate sponte propria digressurus.

Orientis vero limes in longum protentus et rectum ab Euphratis fluminis ripis ad usque supercilia porrigitur Nili, laeva Saracenis conterminans gentibus, dextra pelagi fragoribus patens, quam plagam Nicator Seleucus occupatam auxit magnum in modum, cum post Alexandri Macedonis obitum successorio iure teneret regna Persidis, efficaciae inpetrabilis rex, ut indicat cognomentum.

Sed (saepe enim redeo ad Scipionem, cuius omnis sermo erat de amicitia) querebatur, quod omnibus in rebus homines diligentiores essent; capras et oves quot quisque haberet, dicere posse, amicos quot haberet, non posse dicere et in illis quidem parandis adhibere curam, in amicis eligendis neglegentis esse nec habere quasi signa quaedam et notas, quibus eos qui ad amicitias essent idonei, iudicarent. Sunt igitur firmi et stabiles et constantes eligendi; cuius generis est magna penuria. Et iudicare difficile est sane nisi expertum; experiendum autem est in ipsa amicitia. Ita praecurrit amicitia iudicium tollitque experiendi potestatem.

Thalassius vero ea tempestate praefectus praetorio praesens ipse quoque adrogantis ingenii, considerans incitationem eius ad multorum augeri discrimina, non maturitate vel consiliis mitigabat, ut aliquotiens celsae potestates iras principum molliverunt, sed adversando iurgandoque cum parum congrueret, eum ad rabiem potius evibrabat, Augustum actus eius exaggerando creberrime docens, idque, incertum qua mente, ne lateret adfectans. quibus mox Caesar acrius efferatus, velut contumaciae quoddam vexillum altius erigens, sine respectu salutis alienae vel suae ad vertenda opposita instar rapidi fluminis irrevocabili impetu ferebatur.

image::https://www.planete-secu.com/wp-content/uploads/billet-gestionnaire-mot-passe-dashlane-keepass.svg[]


Circa hos dies Lollianus primae lanuginis adulescens, Lampadi filius ex praefecto, exploratius causam Maximino spectante, convictus codicem noxiarum artium nondum per aetatem firmato consilio descripsisse, exulque mittendus, ut sperabatur, patris inpulsu provocavit ad principem, et iussus ad eius comitatum duci, de fumo, ut aiunt, in flammam traditus Phalangio Baeticae consulari cecidit funesti carnificis manu.

Incenderat autem audaces usque ad insaniam homines ad haec, quae nefariis egere conatibus, Luscus quidam curator urbis subito visus: eosque ut heiulans baiolorum praecentor ad expediendum quod orsi sunt incitans vocibus crebris. qui haut longe postea ideo vivus exustus est.


## Pattern

```
2017-12-30 01:14:59,578 DEBUG c.p.l.LoggerExample \[main\] This is a debug message
2017-12-30 01:14:59,583 INFO c.p.l.LoggerExample \[main\] This is an info message
2017-12-30 01:14:59,584 WARN c.p.l.LoggerExample \[main\] This is an warn message
2017-12-30 01:14:59,584 ERROR c.p.l.LoggerExample \[main\] This is an error message
2017-12-30 01:14:59,584 ERROR c.p.l.LoggerExample \[main\] This is an error message with a stacktrace
java.lang.NullPointerException: null
	at com.planetesecu.loginjection.LoggerExample.main(LoggerExample.java:20) \[classes/:?\]
```
## JSON

```
{
  "timeMillis" : 1514593403852,
  "thread" : "main",
  "level" : "DEBUG",
  "loggerName" : "com.planetesecu.loginjection.LoggerExample",
  "message" : "This is a debug message",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId" : 1,
  "threadPriority" : 5
}
{
  "timeMillis" : 1514593403933,
  "thread" : "main",
  "level" : "INFO",
  "loggerName" : "com.planetesecu.loginjection.LoggerExample",
  "message" : "This is an info message",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId" : 1,
  "threadPriority" : 5
}
{
  "timeMillis" : 1514593403933,
  "thread" : "main",
  "level" : "WARN",
  "loggerName" : "com.planetesecu.loginjection.LoggerExample",
  "message" : "This is an warn message",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId" : 1,
  "threadPriority" : 5
}
{
  "timeMillis" : 1514593403934,
  "thread" : "main",
  "level" : "ERROR",
  "loggerName" : "com.planetesecu.loginjection.LoggerExample",
  "message" : "This is an error message",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId" : 1,
  "threadPriority" : 5
}
{
  "timeMillis" : 1514593403934,
  "thread" : "main",
  "level" : "ERROR",
  "loggerName" : "com.planetesecu.loginjection.LoggerExample",
  "message" : "This is an error message with a stacktrace",
  "thrown" : {
    "commonElementCount" : 0,
    "name" : "java.lang.NullPointerException",
    "extendedStackTrace" : \[ {
      "class" : "com.planetesecu.loginjection.LoggerExample",
      "method" : "main",
      "file" : "LoggerExample.java",
      "line" : 20,
      "exact" : true,
      "location" : "classes/",
      "version" : "?"
    } \]
  },
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId" : 1,
  "threadPriority" : 5
}
```

## CSV

```
0,1514593468196,DEBUG,1,main,5,This is a debug message,org.apache.logging.log4j.spi.AbstractLogger,com.planetesecu.loginjection.LoggerExample,,,com.planetesecu.loginjection.LoggerExample.main(LoggerExample.java:12),{},\[\]
0,1514593468198,INFO,1,main,5,This is an info message,org.apache.logging.log4j.spi.AbstractLogger,com.planetesecu.loginjection.LoggerExample,,,com.planetesecu.loginjection.LoggerExample.main(LoggerExample.java:13),{},\[\]
0,1514593468198,WARN,1,main,5,This is an warn message,org.apache.logging.log4j.spi.AbstractLogger,com.planetesecu.loginjection.LoggerExample,,,com.planetesecu.loginjection.LoggerExample.main(LoggerExample.java:14),{},\[\]
0,1514593468198,ERROR,1,main,5,This is an error message,org.apache.logging.log4j.spi.AbstractLogger,com.planetesecu.loginjection.LoggerExample,,,com.planetesecu.loginjection.LoggerExample.main(LoggerExample.java:15),{},\[\]
0,1514593468198,ERROR,1,main,5,This is an error message with a stacktrace,org.apache.logging.log4j.spi.AbstractLogger,com.planetesecu.loginjection.LoggerExample,,java.lang.NullPointerException,com.planetesecu.loginjection.LoggerExample.main(LoggerExample.java:22),{},\[\]

## XML

<Event
	xmlns="http://logging.apache.org/log4j/2.0/events" timeMillis="1514593844123" thread="main" level="DEBUG" loggerName="com.planetesecu.loginjection.LoggerExample" endOfBatch="false" loggerFqcn="org.apache.logging.log4j.spi.AbstractLogger" threadId="1" threadPriority="5">
	<Message>This is a debug message</Message>
</Event>
<Event
	xmlns="http://logging.apache.org/log4j/2.0/events" timeMillis="1514593844264" thread="main" level="INFO" loggerName="com.planetesecu.loginjection.LoggerExample" endOfBatch="false" loggerFqcn="org.apache.logging.log4j.spi.AbstractLogger" threadId="1" threadPriority="5">
	<Message>This is an info message</Message>
</Event>
<Event
	xmlns="http://logging.apache.org/log4j/2.0/events" timeMillis="1514593844265" thread="main" level="WARN" loggerName="com.planetesecu.loginjection.LoggerExample" endOfBatch="false" loggerFqcn="org.apache.logging.log4j.spi.AbstractLogger" threadId="1" threadPriority="5">
	<Message>This is an warn message</Message>
</Event>
<Event
	xmlns="http://logging.apache.org/log4j/2.0/events" timeMillis="1514593844266" thread="main" level="ERROR" loggerName="com.planetesecu.loginjection.LoggerExample" endOfBatch="false" loggerFqcn="org.apache.logging.log4j.spi.AbstractLogger" threadId="1" threadPriority="5">
	<Message>This is an error message</Message>
</Event>
<Event
	xmlns="http://logging.apache.org/log4j/2.0/events" timeMillis="1514593844268" thread="main" level="ERROR" loggerName="com.planetesecu.loginjection.LoggerExample" endOfBatch="false" loggerFqcn="org.apache.logging.log4j.spi.AbstractLogger" threadId="1" threadPriority="5">
	<Message>This is an error message with a stacktrace</Message>
	<Thrown commonElementCount="0" name="java.lang.NullPointerException">
		<ExtendedStackTrace>
			<ExtendedStackTraceItem class="com.planetesecu.loginjection.LoggerExample" method="main" file="LoggerExample.java" line="20" exact="true" location="classes/" version="?"/>
		</ExtendedStackTrace>
	</Thrown>
</Event>
```

## HTML

```
Log session start time Sat Dec 30 01:27:45 CET 2017

Time

Thread

Level

Logger

Message

462

main

DEBUG

com.planetesecu.loginjection.LoggerExample

This is a debug message

462

main

INFO

com.planetesecu.loginjection.LoggerExample

This is an info message

463

main

**WARN**

com.planetesecu.loginjection.LoggerExample

This is an warn message

463

main

**ERROR**

com.planetesecu.loginjection.LoggerExample

This is an error message

463

main

**ERROR**

com.planetesecu.loginjection.LoggerExample

This is an error message with a stacktrace

java.lang.NullPointerException  
     at 
```

ddd